.TH TURENG 1 tureng\-VERSION
.SH NAME
tureng \- interactive cli dictionary
.SH SYNOPSIS
.B tureng
.RB [ \-v ]
.SH DESCRIPTION
tureng is an interactive command line interfice dictionary. It is
interactive so while you typing the word it is sending requests to the
tureng.com for predictions and printing the curses window interactively.
.SH OPTIONS
.B \-v
prints version information to standart output, then exist.
