#!/bin/sh
#
# Created: 2020 Feb 09 22:54:30 
#
# Requirements:
#   - running: tureng-api (https://github.com/ihsanturk/tureng-api)
#   - jq
#   - curl

mkdir -p ${HOME}/.cache/tureng/

( [ $# -gt 0 ] && echo $@ || cat /dev/stdin ) | while read args; do
	phrase=$(echo $args | sed 's/ /+/g' | tr '[:upper:]' '[:lower:]');
	file=${HOME}/.cache/tureng/$phrase.json;
	if ! [ -s $file ]; then
		pgrep tureng-api &>/dev/null || { echo tureng-api is not up.; exit 1; }
		curl -so $file "localhost:8080/translate/$phrase" ||
			{ >&2 echo "`basename $0`: connection error"; exit 2; }
	fi
	if [[ $(cat $file | jq -r '.response|.[]|.target' | uniq) == "null" ]]; then
		if ! [[ $(cat $file | jq -r '.response|.[]|.tr' | uniq) ]]; then
			>&2 echo "`basename $0`: $phrase: no such phrase"; exit 2;
		else
			cat $file | jq -r '.response|.[]|.tr' | uniq
		fi
	else
		cat $file | jq -r '.response|.[]|.target' | uniq
	fi
done
